#**=====================================================================
#* FileName: GetScreenShot.yml
#* FileInstructions: Github Action自动获取某网站主页截图
#* Attention：开始之前要确保 Github 和 Gitee 中已经保存了本机的公钥.ssh/id_rsa.pub
#* Environment Variables：
#*                       PERSONAL_ACCESS_TOKENS_GITHUB:Github中Personal access tokens
#* =======================================================================*/
name: GetScreenShot
on:
  schedule:
    - cron: '0 0 1 * *' # 定时触发配置（每月1日0时0分运行）
  push:
    branches:
      - master
  # 允许从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:

permissions:   # 设置权限, 允许 GitHub Actions 写入仓库内容
  contents: write

jobs:
  download:
    runs-on: ubuntu-latest
    # 仅当提交信息包含[start]时触发
    if: contains(github.event.head_commit.message, '[start]')
    steps:
    - name: Download
      env:
        SCREEN_SHOT_ADDRESS: https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate
      run: |
        curl ${SCREEN_SHOT_ADDRESS}/https://docs-site.github.io/site-vuepress/ -o site-vuepress.jpg
        curl ${SCREEN_SHOT_ADDRESS}/https://docs-site.github.io/site-vitepress/ -o site-vitepress.jpg
        curl ${SCREEN_SHOT_ADDRESS}/https://hexo.io/ -o hexo.io.jpg
        
        curl https://purge.jsdelivr.net/gh/docs-site/screen-shot@gh-pages/*.*
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKENS_GITHUB }}
        publish_dir: ./
